### ISSUE TITLE
[Question] - Next release

### ISSUE THREAD

**Issue by chubchubsancho** [mehdy/keepalived-exporter#107]
Do you have a release date for `v1.3.0` ?
As this release will include fix for `keepalived_vrrp_state` on keepalived `v2.2.7` https://github.com/mehdy/keepalived-exporter/pull/88

**Comment by mehdy** [comment]
Sure! I'll try to make it happen asap. Sorry for the delay. I've been very busy.
I hope it'll be done within the next week.

**Comment by mehdy** [comment]
You can now get the new version!
https://github.com/mehdy/keepalived-exporter/releases/tag/v1.3.0
