### ISSUE TITLE
No version info for release v1.3.1

### ISSUE THREAD

**Issue by iivanov9** [mehdy/keepalived-exporter#139]
Latest version don't provide version number in metrics:
`keepalived_exporter_build_info{branch="",goarch="amd64",goos="linux",goversion="go1.20.6",revision="11862a54a7f6bb175bfa82312d516b8ff1adccd4",tags="unknown",version=""} 1`
and in command line:
`keepalived-exporter --version
INFO[0000] Keepalived Exporter                           build_time= commit= version=
`

**Comment by mehdy** [comment]
Thanks for reporting. This has been fixed (#136) and will be released in the next version.
