### ISSUE TITLE
Failed to run exporter, error while loading shared libraries

### ISSUE THREAD

**Issue by jura43** [mehdy/keepalived-exporter#172]
Hi, Im having trouble running exporter on some of my servers.

I am getting this error when try to start exporter
```shell
ERRO[0000] Error getting keepalived version              error="exit status 127" stderr="keepalived: error while loading shared libraries: libip4tc.so.0: cannot open shared object file: No such file or directory\n" stdout=
WARN[0000] Version detection failed. Assuming it's the latest one.  error="error getting keepalived version"
FATA[0000] Error getting signum                          error="exit status 127" signal=DATA stderr="keepalived: error while loading shared libraries: libip4tc.so.0: cannot open shared object file: No such file or directory\n"
```

I tried building exporter from source and all possible solutions when googling this error.

**Kernel version**
`Linux server1.local 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Ubuntu version**
`Ubuntu 20.04.2 LTS`

**Comment by clwluvw** [comment]
Hi, What version of keepalived-exporter are you using?

**Comment by jura43** [comment]
> Hi, What version of keepalived-exporter are you using?

The latest one, v1.3.3.

**Comment by clwluvw** [comment]
I'm not sure if this is the keepalived-exporter issue. We have `CGO_ENABLED=0` (https://github.com/mehdy/keepalived-exporter/blob/master/.goreleaser.yaml#L6) when building the binaries. This seems to be your environmental issue.

**Comment by jura43** [comment]
> I'm not sure if this is the keepalived-exporter issue. We have `CGO_ENABLED=0` (https://github.com/mehdy/keepalived-exporter/blob/master/.goreleaser.yaml#L6) when building the binaries. This seems to be your environmental issue.

Thank you for your help. I will close this issue since it is probably issues with enviroment.
