### ISSUE TITLE
./keepalived-exporter: not found

### ISSUE THREAD

**Issue by luoMonkeyKing** [mehdy/keepalived-exporter#65]
Hello, why is the report executed in the docker container./keepalived-exporter: not found

**Comment by clwluvw** [comment]
Which base image do you use for running Keepalived Exporter and also do you use binary released or build it on your own?

**Comment by luoMonkeyKing** [comment]
The basic image of keepalived1.2.2 of alpine is used, and the binary released used is version 1.1.0 on github

**Comment by clwluvw** [comment]
Binaries on the release page are not usable for the alpine OS. you should build it on your own or wait until #54 got merged and then use our own image that is based on alpine too.

**Comment by luoMonkeyKing** [comment]
ok，thanks
