### ISSUE TITLE
Occasional wrong result keepalived_up=0

### ISSUE THREAD

**Issue by bpetermannS11** [mehdy/keepalived-exporter#75]
Occasionally the exporter returns no keepalived metrics and keepalived_up = 0 even though the keepalived works fine.
In the exporter log there are lines

```
level=error msg="keepalived.data and keepalived.stats datas are not synced"
level=error msg="No data found to be exported" error="keepalived.data and keepalived.stats datas are not synced"
```

keepalived-exporter version 1.2.0 on Ubuntu 18.04.5 LTS,
keepalived version is 1.3.9 without support for JSON output, so stats/data is used.

One explanation could be that keepalived takes too long to write the stats or data file after the SIGSTATS/SIGDATA signal. Waiting 10 ms as in keepalived_container_collector_host.go:115 may not always be enough.

**Comment by bondif** [comment]
I have the same problem

**Comment by mehdy** [comment]
Sorry for the very long delay. I'll investigate soon.
